apiVersion: v1
kind: Service
metadata:
    name: "testysaks-edbc"
    labels:
        app: "testysaks-edbc"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "testysaks-edbc"