on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: testys.azurecr.io
        username: ${{ secrets.acr_testys_username }}
        password: ${{ secrets.acr_testys_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t testys.azurecr.io/akstestys:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push testys.azurecr.io/akstestys:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_akstestys_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep akstestys9260 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace akstestys9260`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: akstestys9260
        container-registry-url: testys.azurecr.io
        container-registry-username: ${{ secrets.acr_testys_username }}
        container-registry-password: ${{ secrets.acr_testys_password }}
        secret-name: akstestysdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: akstestys9260
        manifests: |
          manifests/deployment-3.yml
          manifests/service-3.yml
        images: |
          testys.azurecr.io/akstestys:${{ github.sha }}
        imagepullsecrets: |
          akstestysdockerauth
