on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: testys.azurecr.io
        username: ${{ secrets.acr_testys_username }}
        password: ${{ secrets.acr_testys_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t testys.azurecr.io/testysaks:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push testys.azurecr.io/testysaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_testysaks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep testysaksb94b | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace testysaksb94b`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: testysaksb94b
        container-registry-url: testys.azurecr.io
        container-registry-username: ${{ secrets.acr_testys_username }}
        container-registry-password: ${{ secrets.acr_testys_password }}
        secret-name: testysaksdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: testysaksb94b
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          testys.azurecr.io/testysaks:${{ github.sha }}
        imagepullsecrets: |
          testysaksdockerauth
